#!/usr/bin/env python
# coding: utf-8

# In[ ]:


import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0"


# In[ ]:


os.environ["HOME"] = "/mnt/nas/shuvranshu"
os.environ["HF_HOME"] = "/mnt/nas/shuvranshu/huggingface_cache"
os.environ["TRANSFORMERS_CACHE"] = "/mnt/nas/shuvranshu/huggingface_cache"
os.environ["HF_DATASETS_CACHE"] = "/mnt/nas/shuvranshu/huggingface_cache"
os.environ["XDG_CACHE_HOME"] = "/mnt/nas/shuvranshu/huggingface_cache"
os.makedirs("/mnt/nas/shuvranshu/huggingface_cache", exist_ok=True)


# In[4]:


import warnings
warnings.filterwarnings("ignore")
os.environ["TRANSFORMERS_VERBOSITY"] = "error"
os.environ["TOKENIZERS_PARALLELISM"] = "false"


# In[5]:


import json
import re
import string
import argparse
import logging
from copy import deepcopy
from typing import List, Tuple
from collections import Counter
from dataclasses import dataclass, field

import numpy as np
import torch
from datasets import load_dataset

from transformers import AutoTokenizer, AutoModelForCausalLM, GenerationConfig
import transformers
transformers.logging.set_verbosity_error()

from peft import PeftModel

from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_core.prompts import PromptTemplate

from dotenv import load_dotenv
load_dotenv()
hf_token = os.getenv("HF_TOKEN")
if hf_token:
    os.environ["HUGGINGFACEHUB_API_TOKEN"] = hf_token

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger(__name__)

# Silence noisy loggers
for noisy in ["httpx", "httpcore", "urllib3", "sentence_transformers",
              "faiss", "langchain", "huggingface_hub"]:
    logging.getLogger(noisy).setLevel(logging.WARNING)


# In[6]:


class Config:
    # --- Model: Base + LoRA adapter (no merged model needed) ---
    BASE_MODEL = "meta-llama/Llama-3.1-8B-Instruct"
    ADAPTER_PATH = "/mnt/nas/shuvranshu/corag_finetuned/corag_lora_adapter"
 
    # --- Dataset ---
    DATASET_NAME = "rajpurkar/squad_v2"
    EVAL_SPLIT = "validation[:100]"       
 
    # --- Retrieval (LangChain FAISS) ---
    EMBEDDING_MODEL = "sentence-transformers/all-MiniLM-L6-v2"
    FAISS_PATH = "/mnt/nas/shuvranshu/corag_finetuned/corag_faiss_index"
    RETRIEVER_TOP_K = 5                  
    CHUNK_SIZE = 800
    CHUNK_OVERLAP = 100
 
    # --- CoRAG Decoding (Section 3.3) ---
    MAX_CHAIN_LENGTH = 6                  # L
    NUM_SAMPLES = 4                       # N for best-of-N
    SAMPLING_TEMP = 0.7                   # temperature for sampling strategies
 
    # --- Tree Search ---
    TREE_EXPANSION = 4
    TREE_ROLLOUTS = 2
    TREE_ROLLOUT_DEPTH = 2
 
    # --- Output ---
    RESULTS_PATH = "/mnt/nas/shuvranshu/law_rag/corag_results.json"


# In[7]:


TASK_DESC = "answer questions from the SQuAD v2 dataset"

def fmt_sub_query_prompt(query: str, intermediate_qa: str) -> str:
    return f"""You are using a search engine to answer the main query by iteratively searching the web. Given the following intermediate queries and answers, generate a new simple follow-up question that can help answer the main query. You may rephrase or decompose the main query when previous answers are not helpful. Ask simple follow-up questions only as the search engine may not understand complex questions.

## Previous intermediate queries and answers
{intermediate_qa}

## Task description
{TASK_DESC}

## Main query to answer
{query}

Respond with a simple follow-up question that will help answer the main query, do not explain yourself or output anything else."""


def fmt_sub_answer_prompt(sub_query: str, documents: str) -> str:
    return f"""Given the following documents, generate an appropriate answer for the query. DO NOT hallucinate any information, only use the provided documents to generate the answer. Respond "No relevant information found" if the documents do not contain useful information.

## Documents
{documents}

## Query
{sub_query}

Respond with a concise answer only, do not explain yourself or output anything else."""


def fmt_final_answer_prompt(query: str, intermediate_qa: str, documents: str) -> str:
    return f"""Given the following intermediate queries and answers, generate a final answer for the main query by combining relevant information. Note that intermediate answers are generated by an LLM and may not always be accurate.

## Documents
{documents}

## Intermediate queries and answers
{intermediate_qa}

## Task description
{TASK_DESC}

## Main query
{query}

Respond with an appropriate answer only, do not explain yourself or output anything else."""


def fmt_baseline_prompt(query: str, documents: str) -> str:
    return f"""You are a factual assistant whose goal is to produce answers strictly supported by the provided context.

Instructions:
1. Use ONLY the information present in the provided context.
2. Do NOT introduce external knowledge.
3. If the answer cannot be found in the context, don't give any answer.
4. Ensure the answer directly addresses the question.
5. Answer in maximum 3 to 5 words.

Context:
{documents}

Question:
{query}

Answer:"""


def format_intermediate_qa(steps: list) -> str:
    if not steps:
        return "None"
    lines = []
    for i, s in enumerate(steps, 1):
        lines.append(f"Q{i}: {s['sub_query']}")
        lines.append(f"A{i}: {s['sub_answer']}")
    return "\n".join(lines)


def format_docs(docs: List[str]) -> str:
    return "\n\n".join([f"Document {i+1}: {d}" for i, d in enumerate(docs)])


# In[8]:


@dataclass
class RetrievalStep:
    sub_query: str
    sub_answer: str
    retrieved_docs: List[str] = field(default_factory=list)

@dataclass
class RetrievalChain:
    query: str
    steps: List[RetrievalStep] = field(default_factory=list)
    final_answer: str = ""
    penalty_score: float = float('inf')

    def get_intermediate_qa(self) -> str:
        return format_intermediate_qa(
            [{"sub_query": s.sub_query, "sub_answer": s.sub_answer} for s in self.steps]
        )

    def get_all_docs(self) -> str:
        seen = set()
        docs = []
        for step in self.steps:
            for doc in step.retrieved_docs:
                if doc not in seen:
                    seen.add(doc)
                    docs.append(doc)
        return format_docs(docs[:15])


# In[9]:


def load_model():
    """
    Load base Llama 3.1 8B + LoRA adapter via PeftModel.
    """

    # Load tokenizer from adapter dir
    tokenizer = AutoTokenizer.from_pretrained(
        Config.BASE_MODEL,
        trust_remote_code=True
    )

    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    tokenizer.padding_side = "right"

    # Load BASE model first
    print(f"Loading base model: {Config.BASE_MODEL}")
    base_model = AutoModelForCausalLM.from_pretrained(
        Config.BASE_MODEL,
        torch_dtype=torch.float16,
        device_map={"":0},
        trust_remote_code=True
    )

    # Load LoRA adapter on top
    print(f"Loading LoRA adapter: {Config.ADAPTER_PATH}")
    model = PeftModel.from_pretrained(base_model, Config.ADAPTER_PATH)
    model.eval()

    print(f"Model on: {next(model.parameters()).device}, GPU: {torch.cuda.get_device_name(0)}")

    gen_greedy = GenerationConfig(max_new_tokens=128, do_sample=False, repetition_penalty=1.2)
    gen_sample = GenerationConfig(max_new_tokens=128, do_sample=True,
                              temperature=Config.SAMPLING_TEMP, top_p=0.9,
                              repetition_penalty=1.2)

    return tokenizer, model, gen_greedy, gen_sample


# In[10]:


def build_vectorstore(dataset_split) -> FAISS:
    """Build FAISS index from SQuAD v2 validation contexts."""
    logger.info("Building FAISS vector store from evaluation contexts...")

    all_text = ""
    seen = set()
    for row in dataset_split:
        ctx = row["context"].strip()
        if ctx not in seen:
            seen.add(ctx)
            all_text += ctx + "\n"

    splitter = RecursiveCharacterTextSplitter(
        chunk_size=Config.CHUNK_SIZE,
        chunk_overlap=Config.CHUNK_OVERLAP,
        separators=["\n\n", "\n", " ", ""]
    )
    chunks = splitter.split_text(all_text)
    logger.info(f"Total chunks: {len(chunks)}")

    embeddings = HuggingFaceEmbeddings(
        model_name=Config.EMBEDDING_MODEL,
        model_kwargs={"device": "cuda:0"},
        encode_kwargs={"normalize_embeddings": True}
    )

    vectorstore = FAISS.from_texts(chunks, embeddings)
    logger.info(f"FAISS index built with {vectorstore.index.ntotal} vectors")
    return vectorstore


def load_vectorstore() -> FAISS:
    """Load existing FAISS index."""
    embeddings = HuggingFaceEmbeddings(
        model_name=Config.EMBEDDING_MODEL,
        model_kwargs={"device": "cuda:0"},
        encode_kwargs={"normalize_embeddings": True}
    )
    return FAISS.load_local(
        Config.FAISS_PATH, embeddings,
        allow_dangerous_deserialization=True
    )


def retrieve_docs(vectorstore, query: str, top_k: int = None) -> List[str]:
    """Retrieve top-k documents using LangChain FAISS retriever."""
    k = top_k or Config.RETRIEVER_TOP_K
    retriever = vectorstore.as_retriever(
        search_type="similarity",
        search_kwargs={"k": k}
    )
    docs = retriever.invoke(query)
    return [d.page_content for d in docs]


# In[11]:


def generate_text(model, tokenizer, prompt, gen_config):
    try:
        inputs = tokenizer(prompt, return_tensors="pt", truncation=True, max_length=2048)
        inputs = {k: v.to(model.device) for k, v in inputs.items()}

        with torch.no_grad():
            output_ids = model.generate(
                **inputs,
                generation_config=gen_config,
                pad_token_id=tokenizer.eos_token_id,
            )

        new_tokens = output_ids[0, inputs["input_ids"].shape[1]:]
        text = tokenizer.decode(new_tokens, skip_special_tokens=True).strip()

        # Clean: take only first sentence/line, remove repeated fragments
        lines = [l.strip() for l in text.split("\n") if l.strip()]
        for line in lines:
            if not line.startswith("#") and len(line) > 2:
                text = line
                break
        else:
            text = lines[0] if lines else ""

        # Cut off at first repetition pattern
        words = text.split()
        clean_words = []
        for w in words:
            clean_words.append(w)
            # If the last 3+ words repeat, stop
            if len(clean_words) >= 6:
                half = len(clean_words) // 2
                if clean_words[-half:] == clean_words[-2*half:-half]:
                    clean_words = clean_words[:-half]
                    break
        text = " ".join(clean_words)

        # Remove "## Step" artifacts from base model
        if "##" in text:
            text = text.split("##")[0].strip()

        return text
    except Exception as e:
        print(f"Generation error: {e}")
        return ""


# In[12]:


def compute_penalty(chain: RetrievalChain) -> float:
    """
    From Section 3.3: Penalty = fraction of steps returning no useful info.
    Lower penalty = better chain.
    """
    if not chain.steps:
        return float('inf')
    no_info = 0
    for step in chain.steps:
        ans = step.sub_answer.lower()
        if ("no relevant information" in ans or "not found" in ans or
            "no information" in ans or ans.strip() == ""):
            no_info += 1
    return no_info / len(chain.steps)


# In[13]:


def corag_greedy(
    query: str, vectorstore, model, tokenizer,
    gen_greedy, gen_sample, max_length: int = None
) -> RetrievalChain:
    """
    Greedy Decoding: Generate L sub-queries sequentially with greedy decoding.
    """
    L = max_length or Config.MAX_CHAIN_LENGTH
    chain = RetrievalChain(query=query)

    for _ in range(L):
        sq_prompt = fmt_sub_query_prompt(query, chain.get_intermediate_qa())
        sub_query = generate_text(model, tokenizer, sq_prompt, gen_greedy)
        if not sub_query:
            break

        existing = {s.sub_query.lower() for s in chain.steps}
        if sub_query.lower() in existing:
            break

        # Retrieve via LangChain + generate sub-answer
        docs = retrieve_docs(vectorstore, sub_query)
        sa_prompt = fmt_sub_answer_prompt(sub_query, format_docs(docs))
        sub_answer = generate_text(model, tokenizer, sa_prompt, gen_greedy)

        chain.steps.append(RetrievalStep(sub_query, sub_answer, docs))

    # Final answer with original query docs + chain docs
    orig_docs = retrieve_docs(vectorstore, query)
    all_docs = format_docs(orig_docs[:5]) + "\n\n" + chain.get_all_docs()
    fa_prompt = fmt_final_answer_prompt(query, chain.get_intermediate_qa(), all_docs)
    chain.final_answer = generate_text(model, tokenizer, fa_prompt, gen_greedy)
    chain.penalty_score = compute_penalty(chain)
    return chain


# In[14]:


def corag_best_of_n(
    query: str, vectorstore, model, tokenizer,
    gen_greedy, gen_sample,
    N: int = None, max_length: int = None
) -> RetrievalChain:
    """
    Best-of-N Sampling: Sample N chains with temperature, pick lowest penalty.
    """
    N = N or Config.NUM_SAMPLES
    L = max_length or Config.MAX_CHAIN_LENGTH

    chains = []
    for _ in range(N):
        chain = RetrievalChain(query=query)
        for _ in range(L):
            sq_prompt = fmt_sub_query_prompt(query, chain.get_intermediate_qa())
            sub_query = generate_text(model, tokenizer, sq_prompt, gen_sample)
            if not sub_query:
                break
            existing = {s.sub_query.lower() for s in chain.steps}
            if sub_query.lower() in existing:
                break

            docs = retrieve_docs(vectorstore, sub_query)
            sa_prompt = fmt_sub_answer_prompt(sub_query, format_docs(docs))
            sub_answer = generate_text(model, tokenizer, sa_prompt, gen_greedy)
            chain.steps.append(RetrievalStep(sub_query, sub_answer, docs))

        chain.penalty_score = compute_penalty(chain)
        chains.append(chain)

    # Select best chain (lowest penalty)
    best = min(chains, key=lambda c: c.penalty_score)

    # Final answer only for the best chain
    orig_docs = retrieve_docs(vectorstore, query)
    all_docs = format_docs(orig_docs[:5]) + "\n\n" + best.get_all_docs()
    fa_prompt = fmt_final_answer_prompt(query, best.get_intermediate_qa(), all_docs)
    best.final_answer = generate_text(model, tokenizer, fa_prompt, gen_greedy)
    return best


# In[15]:


def corag_tree_search(
    query: str, vectorstore, model, tokenizer,
    gen_greedy, gen_sample, max_length: int = None
) -> RetrievalChain:
    """
    Tree Search (BFS with rollouts):
    At each step, expand by sampling several sub-queries.
    For each, perform rollouts to estimate quality. Keep the best.
    """
    L = max_length or Config.MAX_CHAIN_LENGTH
    exp_size = Config.TREE_EXPANSION
    n_rollouts = Config.TREE_ROLLOUTS
    rollout_depth = Config.TREE_ROLLOUT_DEPTH

    current = RetrievalChain(query=query)

    for depth in range(L):
        candidates = []

        for _ in range(exp_size):
            sq_prompt = fmt_sub_query_prompt(query, current.get_intermediate_qa())
            sub_query = generate_text(model, tokenizer, sq_prompt, gen_sample)
            if not sub_query:
                continue
            existing = {s.sub_query.lower() for s in current.steps}
            if sub_query.lower() in existing:
                continue

            docs = retrieve_docs(vectorstore, sub_query)
            sa_prompt = fmt_sub_answer_prompt(sub_query, format_docs(docs))
            sub_answer = generate_text(model, tokenizer, sa_prompt, gen_greedy)

            expanded = RetrievalChain(
                query=query,
                steps=deepcopy(current.steps) + [RetrievalStep(sub_query, sub_answer, docs)]
            )

            # Rollouts to estimate quality
            rollout_penalties = []
            for _ in range(n_rollouts):
                rollout = RetrievalChain(query=query, steps=deepcopy(expanded.steps))
                for _ in range(rollout_depth):
                    rq_prompt = fmt_sub_query_prompt(query, rollout.get_intermediate_qa())
                    rq = generate_text(model, tokenizer, rq_prompt, gen_sample)
                    if not rq:
                        break
                    r_existing = {s.sub_query.lower() for s in rollout.steps}
                    if rq.lower() in r_existing:
                        break
                    rd = retrieve_docs(vectorstore, rq)
                    ra_prompt = fmt_sub_answer_prompt(rq, format_docs(rd))
                    ra = generate_text(model, tokenizer, ra_prompt, gen_greedy)
                    rollout.steps.append(RetrievalStep(rq, ra, rd))
                rollout_penalties.append(compute_penalty(rollout))

            avg_pen = np.mean(rollout_penalties) if rollout_penalties else float('inf')
            candidates.append((expanded, avg_pen))

        if not candidates:
            break

        best_exp, _ = min(candidates, key=lambda x: x[1])
        current = best_exp

    # Final answer
    orig_docs = retrieve_docs(vectorstore, query)
    all_docs = format_docs(orig_docs[:5]) + "\n\n" + current.get_all_docs()
    fa_prompt = fmt_final_answer_prompt(query, current.get_intermediate_qa(), all_docs)
    current.final_answer = generate_text(model, tokenizer, fa_prompt, gen_greedy)
    current.penalty_score = compute_penalty(current)
    return current


# In[16]:


def baseline_rag(query, vectorstore, model, tokenizer, gen_greedy):
    docs = retrieve_docs(vectorstore, query)
    prompt = fmt_baseline_prompt(query, format_docs(docs))
    return generate_text(model, tokenizer, prompt, gen_greedy)


# In[17]:


def normalize_answer(s: str) -> str:
    """Normalize answer for evaluation (from SQuAD eval script)."""
    s = s.strip().lower()
    s = re.sub(r'\b(a|an|the)\b', ' ', s)
    # Remove punctuation
    s = ''.join(ch for ch in s if ch not in set(string.punctuation))
    # Fix whitespace
    s = ' '.join(s.split())
    if s in ["no answer", "no answers", "n/a", "no relevant information found", ""]:
        return ""
    return s


def compute_em(pred: str, gt: str) -> int:
    """Exact Match score (Section 4.1)."""
    return int(normalize_answer(pred) == normalize_answer(gt))


def compute_f1(pred: str, gt: str) -> float:
    """Token-level F1 score (Section 4.1)."""
    p_tok = normalize_answer(pred).split()
    g_tok = normalize_answer(gt).split()
    if not g_tok:
        return 1.0 if not p_tok else 0.0
    if not p_tok:
        return 0.0
    common = Counter(p_tok) & Counter(g_tok)
    nc = sum(common.values())
    if nc == 0:
        return 0.0
    prec = nc / len(p_tok)
    rec = nc / len(g_tok)
    return 2 * prec * rec / (prec + rec)


def compute_substring(pred: str, gt: str) -> int:
    """Substring match (your original metric)."""
    p, g = normalize_answer(pred), normalize_answer(gt)
    if not g:
        return 1 if not p else 0
    return int(g in p)


# In[18]:


def run_evaluation(
    questions, ground_truths, vectorstore,
    model, tokenizer, gen_greedy, gen_sample,
    strategy="greedy", max_length=6, num_samples=4,
    verbose=True
):
    """Run evaluation and also return retrieved contexts."""
    
    predictions = []
    chain_lengths = []
    all_contexts = []   # NEW

    for i, (q, gt) in enumerate(zip(questions, ground_truths)):

        if strategy == "baseline":
            docs = retrieve_docs(vectorstore, q)
            answer = baseline_rag(q, vectorstore, model, tokenizer, gen_greedy)
            chain_len = 0
            contexts = docs   # baseline context

        elif strategy == "greedy":
            chain = corag_greedy(
                q, vectorstore, model, tokenizer,
                gen_greedy, gen_sample, max_length
            )
            answer = chain.final_answer
            chain_len = len(chain.steps)

            # collect all retrieved docs from chain
            contexts = []
            for step in chain.steps:
                contexts.extend(step.retrieved_docs)

        elif strategy == "best_of_n":
            chain = corag_best_of_n(
                q, vectorstore, model, tokenizer,
                gen_greedy, gen_sample, num_samples, max_length
            )
            answer = chain.final_answer
            chain_len = len(chain.steps)

            contexts = []
            for step in chain.steps:
                contexts.extend(step.retrieved_docs)

        elif strategy == "tree_search":
            chain = corag_tree_search(
                q, vectorstore, model, tokenizer,
                gen_greedy, gen_sample, max_length
            )
            answer = chain.final_answer
            chain_len = len(chain.steps)

            contexts = []
            for step in chain.steps:
                contexts.extend(step.retrieved_docs)

        else:
            raise ValueError(f"Unknown strategy: {strategy}")

        predictions.append(answer)
        chain_lengths.append(chain_len)
        all_contexts.append(contexts)   #  store contexts

        if verbose:
            print(f"\n[{i+1}/{len(questions)}] Q: {q}")
            print(f"  GT: {gt}")
            print(f"  Pred: {answer}")

            if strategy != "baseline":
                print(f"  Chain steps: {chain_len}")
                for j, step in enumerate(chain.steps):
                    print(f"    Step {j+1}: Q='{step.sub_query}' -> A='{step.sub_answer}'")

    # ---- Metrics ----
    em = [compute_em(p, g) for p, g in zip(predictions, ground_truths)]
    f1 = [compute_f1(p, g) for p, g in zip(predictions, ground_truths)]
    sub = [compute_substring(p, g) for p, g in zip(predictions, ground_truths)]

    results = {
        "strategy": strategy,
        "chain_length": max_length,
        "num_samples": num_samples if strategy == "best_of_n" else None,
        "em": float(np.mean(em)),
        "f1": float(np.mean(f1)),
        "substring": float(np.mean(sub)),
        "avg_chain_len": float(np.mean(chain_lengths)),
        "num_questions": len(questions)
    }

    print(f"\n{'='*60}")
    print(f"Results: {strategy} (L={max_length})")
    print(f"{'='*60}")
    print(f"  Exact Match:    {results['em']:.4f}")
    print(f"  F1 Score:       {results['f1']:.4f}")
    print(f"  Substring:      {results['substring']:.4f}")
    print(f"  Avg Chain Len:  {results['avg_chain_len']:.1f}")
    print(f"{'='*60}\n")

    #  RETURN CONTEXTS ALSO
    return results, predictions, all_contexts


# In[19]:

def main():

    dataset = load_dataset(Config.DATASET_NAME, split=Config.EVAL_SPLIT)

    questions = [row["question"] for row in dataset]
    ground_truths = [
        row["answers"]["text"][0] if row["answers"]["text"] else ""
        for row in dataset
    ]

    tokenizer, model, gen_greedy, gen_sample = load_model()

    vectorstore = build_vectorstore(dataset)


    # In[20]:


    results, preds, contexts = run_evaluation(
        questions,
        ground_truths,
        vectorstore,
        model,
        tokenizer,
        gen_greedy,
        gen_sample,
        strategy="greedy",
        max_length=3,   
        verbose=True
    )


# In[ ]:


    dataset_ragas = []

    for q, ctx, ans, ref in zip(questions, contexts, preds, ground_truths):
        dataset_ragas.append({
            "user_input": q,
            "retrieved_contexts": ctx if isinstance(ctx, list) else [ctx],
            "response": ans,
            "reference": ref
        })


    # In[ ]:


    from ragas import EvaluationDataset
    evaluation_dataset = EvaluationDataset.from_list(dataset_ragas)


    # In[ ]:


    from langchain_community.chat_models import ChatOllama
    from langchain_core.prompts import ChatPromptTemplate
    from ragas import evaluate
    from langchain_community.embeddings import OllamaEmbeddings
    from ragas.metrics import LLMContextRecall, Faithfulness, FactualCorrectness


    # In[ ]:


    json_prompt = """
    You are a strict JSON output generator used for evaluation in RAG systems.
    You must always reply ONLY with a valid JSON object — no explanations, no extra text.

    If the question asks for a score, output: {"score": <float between 0 and 1>}
    If the question asks for a label (e.g., yes/no), output: {"label": "yes"} or {"label": "no"}
    Do not include extra keys, comments, or markdown fences.
    """
    langchain_llm= ChatOllama(model="mistral",temperature=0,system=json_prompt)


    langchain_embeddings=OllamaEmbeddings(model="nomic-embed-text")


    # In[ ]:


    result = evaluate(dataset=evaluation_dataset,
                    batch_size=2,
                    #   metrics=[ LLMContextRecall(), Faithfulness(),FactualCorrectness()],
                    metrics=[LLMContextRecall(), Faithfulness(), FactualCorrectness()],
                    llm=langchain_llm,embeddings=langchain_embeddings)
    print(result)


    # In[ ]:


    # Answer similarity using sentence-transformers
    from sentence_transformers import SentenceTransformer, util
    import torch

    qa_model = SentenceTransformer("multi-qa-MiniLM-L6-cos-v1", device="cuda:0")


    # In[ ]:


    sim_scores = []
    skipped = 0

    for pred, gt in zip(preds, ground_truths):
        norm_pred = normalize_answer(pred)
        norm_gt = normalize_answer(gt)

        if not norm_gt and not norm_pred:
            sim_scores.append(1.0)
            continue

        if not norm_gt:
            skipped += 1
            continue

        if not norm_pred:
            sim_scores.append(0.0)
            continue

        ref_emb = qa_model.encode(gt, convert_to_tensor=True)
        ans_emb = qa_model.encode(pred, convert_to_tensor=True)
        score = util.cos_sim(ref_emb, ans_emb).item()
        sim_scores.append(score)

    print(f"Skipped {skipped} samples")
    print(f"Valid samples: {len(sim_scores)}/{len(preds)}")
    print(f"Answer Similarity (cosine): {np.mean(sim_scores):.4f}")

if __name__ == "__main__":
    main()